services:
  prunemate:
    image: anoniemerd/prunemate:latest
    container_name: prunemate
    network_mode: host
    ports:
      - "${PRUNEMATE_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/var/log
      - ${PRUNEMATE_CONFIG_DIR}:/config
    environment:
      - PRUNEMATE_TZ=${TZ}
      - PRUNEMATE_TIME_24H=${PRUNEMATE_TIME_24H}
    restart: unless-stopped