services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: ${FLARESOLVERR_CONTAINER_NAME}
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_HTML=${LOG_HTML}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER}
      - TZ=${TZ}
    ports:
      - "${FLARESOLVERR_PORT}:8191"
    networks:
      - media_network
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: ${QBITTORRENT_CONTAINER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}  
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    volumes:
      - ${QBITTORRENT_CONFIG_DIR}:/config
      - ${DATA_DIR}:/media/storagedrive/data
    ports:
      - "${QBITTORRENT_WEBUI_PORT}:8701"
      - "${QBITTORRENT_TORRENTING_PORT}:50413"
      - "${QBITTORRENT_TORRENTING_PORT}:50413/udp"
    networks:
      - media_network
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: ${PROWLARR_CONTAINER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PROWLARR_CONFIG_DIR}:/config
    ports:
      - "${PROWLARR_PORT}:9696"
    networks:
      - media_network
    depends_on:
      - qbittorrent
      - flaresolverr
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: ${SONARR_CONTAINER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SONARR_CONFIG_DIR}:/config
      - ${DATA_DIR}:/media/storagedrive/data
    ports:
      - "${SONARR_PORT}:8989"
    networks:
      - media_network
    depends_on:
      - qbittorrent
      - flaresolverr
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: ${RADARR_CONTAINER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RADARR_CONFIG_DIR}:/config
      - ${DATA_DIR}:/media/storagedrive/data
    ports:
      - "${RADARR_PORT}:7878"
    networks:
      - media_network
    depends_on:
      - qbittorrent
      - flaresolverr
    restart: unless-stopped

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "${PROFILARR_PORT}:6868"
    volumes:
      - ${PROFILARR_CONFIG_DIR}:/config
    networks:
      - media_network
    restart: unless-stopped

  boxarr:
    image: ghcr.io/iongpt/boxarr:latest
    container_name: boxarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - BOXARR_URL_BASE=${BOXARR_URL_BASE}
    ports:
      - "${BOXARR_PORT}:8888"
    volumes:
      - ${BOXARR_CONFIG_DIR}:/config
    networks:
      - media_network
    restart: unless-stopped
    

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: ${BAZARR_CONTAINER_NAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BAZARR_CONFIG_DIR}:/config
      - ${DATA_DIR}:/media/storagedrive/data
    ports:
      - "${BAZARR_PORT}:6767"
    networks:
      - media_network
    restart: unless-stopped

networks:
  media_network:
    name: media_network