services:
  crafty:
    container_name: ${CONTAINER_NAME}
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    network_mode: ${NETWORK_MODE}
    environment:
        - TZ=${TZ}
    ports:
        - "${CRAFTY_HTTPS_PORT}:8443"
        - "${CRAFTY_DYNMAP_PORT}:8123"
        - "${CRAFTY_BEDROCK_PORT}:19132/udp"
        - "${CRAFTY_MC_PORT_RANGE}:25500-25600"
    volumes:
        - ${CRAFTY_BACKUPS}:/crafty/backups
        - ${CRAFTY_LOGS}:/crafty/logs
        - ${CRAFTY_SERVERS}:/crafty/servers
        - ${CRAFTY_CONFIG}:/crafty/app/config
        - ${CRAFTY_IMPORT}:/crafty/import