services:
  portracker:
    image: mostafawahied/portracker:latest
    container_name: portracker
    restart: unless-stopped
    pid: "host"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - TZ=${TZ}
      - DATABASE_PATH=${DATABASE_PATH}
      - ENABLE_AUTH=${ENABLE_AUTH}
      - SESSION_SECRET=${SESSION_SECRET}
      - INCLUDE_UDP=${INCLUDE_UDP}
      - DEBUG=${DEBUG}
    volumes:
      - ${PORTTRACKER_DATA_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${PORTTRACKER_PORT}:4999"
    networks:
      - portracker

networks:
  portracker:
    driver: bridge
    