services:
  homarr:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMARR_CONFIG_DIR}:/app/data/configs
      - ${HOMARR_ICONS_DIR}:/app/public/icons
      - ${HOMARR_DATA_DIR}:/data
    ports:
      - ${HOMARR_PORT}:7575