services:
  homarr:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMARR_APPDATA_DIR}:/appdata
    ports:
      - ${HOMARR_PORT}:7575