services:
  consumet-api:
    image: "riimuru/consumet-api"
    container_name: "consumet-api"
    restart: unless-stopped
    ports:
      - "30243:3000"
    environment:
      - "NODE_ENV=PROD"
      - "TZ=America/Argentina/Buenos_Aires"
      - "PUID=1000"
      - "PGID=1000"
    networks:
      - media_network

networks:
    media_network:
        name: media_network
