services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: ${CONTAINER_NAME}
    network_mode: ${NETWORK_MODE}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHEDSERVERURL} #optional
      - /dev/dri:/dev/dri
    volumes:
      - ${JELLYFIN_CONFIG_DIR}:/config
      - ${JELLYFIN_MEDIA_DIR}:/media/storagedrive/data
    ports:
      - ${JELLYFIN_PORT}:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped
