services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "${METUBE_PORT}:8081"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOWNLOAD_MODE=${DOWNLOAD_MODE}
      - DOWNLOAD_DIR=${DOWNLOAD_DIR}
      - AUDIO_DOWNLOAD_DIR=${AUDIO_DOWNLOAD_DIR}
      - DOWNLOAD_DIRS_INDEXABLE=${DOWNLOAD_DIRS_INDEXABLE}
    networks:
      - media_network
    volumes:
      - ${METUBE_DATA_DIR}:/media/storagedrive/data/media

networks:
  media_network:
    name: media_network