services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION}
    restart: unless-stopped
    volumes:
      - ${KARAKEEP_DATA_DIR}:/data
    ports:
      - ${KARAKEEP_PORT}:3000
    environment:
      - MEILI_ADDR=http://meilisearch:7700
      - BROWSER_WEB_URL=http://chrome:9222
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      - DATA_DIR=/data # DON'T CHANGE THIS
    networks:
      - karakeep-network
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - karakeep-network
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ${MEILISEARCH_DATA_DIR}:/meili_data
    networks:
      - karakeep-network

networks:
  karakeep-network:
    driver: bridge