services:
  postgres:
    image: postgres:16-alpine
    container_name: cupidoflowers_ims_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cupidoflowers-ims
    ports:
      - "39010:5432"
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d cupidoflowers-ims"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

networks:
  postgres-network:
    driver: bridge