services:
  wizarr:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/wizarrrr/wizarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DISABLE_BUILTIN_AUTH=${WIZARR_DISABLE_BUILTIN_AUTH}
      - TZ=${TZ}
    ports:
      - ${WIZARR_PORT}:5690
    networks:
      - media_network
    volumes:
      - ${WIZARR_CONFIG_DIR}:/data

networks:
  media_network:
    name: media_network